### ISSUE TITLE
Definir front end

### ISSUE THREAD

**Issue by jcserracampos** [100DiasdeCodigo/animelist#2]
Qual tecnologia usar?
Sugestões recebidas no #DevsOnBeer de ser em React

**Comment by Niddhogur** [comment]
Eu estou trabalhando com o React há poucas semanas, então por mim sem problemas. O @fang0rnz tem experiência há um tempo já, seria de grande ajuda :) Outra possibilidade é [Vue](https://vuejs.org), mas envolveria uma curva de aprendizado maior da minha parte!

**Comment by fang0rnz** [comment]
Vue é mais amigável pra galera que não tem experiência com javascript em geral e é mais próximo do HTML, é uma opção interessante. De qualquer forma acho uma boa deixar a galera opinar, se todos estiverem ok com react, simbora

**Comment by jcserracampos** [comment]
React ou Vue?
Estamos neste dilema então?

**Comment by rafaelvebercarvalho** [comment]
Eu voto no react

**Comment by eduardofg87** [comment]
Acho que seria interessante os 2, quem quiser aprender/tiver xp em Vue ou React implemente um pouco de cada. Assim tendo os 2 frontend em Vue e React. Acredio que ajudaria no aprendizado.

**Comment by jcserracampos** [comment]
Tendo em vista que o back end ficou em Node.js, acho que o frontend em React ia ser um bom exercício do stack que mais andam pedindo.
Assim, fica fácil para quem quiser arrumar um emprego depois dos 100 dias.

**Comment by eduardofg87** [comment]
É uma ótima ideia!

**Comment by jcserracampos** [comment]
Votação até segunda, 18 de junho, 23:59h.

Dê like 👍  aqui para votar em **REACT**
Dê heart ❤️ para aqui para votar em **VUE**

**Comment by jcserracampos** [comment]
Vitória do Vue.
