### ISSUE TITLE
Criar esqueleto da aplicação

### ISSUE THREAD

**Issue by jcserracampos** [100DiasdeCodigo/animelist#8]
Como definido em #1, o backend será em Node.js.
Agora é necessário criar a aplicação.

Talvez usar ES6?

**Comment by Rarfael** [comment]
Eu não consigo encontrar motivos para não usar ES6, visto que sera em node e provavelmente em uma das versões que suporta.

**Comment by jcserracampos** [comment]
Como faremos com o front end?
Para quem tem mais experiência com Vue, faremos as views serem entregues pelo back end ou faremos tudo via API?

**Comment by jcserracampos** [comment]
Feito.
